version: '3.9'

services:
  django_app:
    container_name: django_app
    build:
      context: .
    ports:
      - "3000:8000"
    volumes:
      - ./django_app:/django_app
      - staticfiles:/django_app/staticfiles
    env_file:
      - ./dotenv_files/.env
    environment:
      - RUN_MODE=web
    depends_on:
      - django_psql
      - redis
    restart: unless-stopped

  django_psql:
    container_name: django_psql
    image: postgres:16-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - ./dotenv_files/.env
    ports:
      - "3001:5432"
    environment:
      - TZ=America/Sao_Paulo
    restart: unless-stopped

  redis:
    container_name: redis
    image: redis:7-alpine
    volumes:
      - redis_data:/data
    env_file:
      - ./dotenv_files/.env
    ports:
      - "3002:6379"
    environment:
      - TZ=America/Sao_Paulo
    command: ["redis-server", "--appendonly", "yes"]
    restart: unless-stopped

  celery:
    container_name: celery
    build:
      context: .
    volumes:
      - ./django_app:/django_app
    env_file:
      - ./dotenv_files/.env
    environment:
      - RUN_MODE=celery
    depends_on:
      - django_psql
      - redis
    restart: unless-stopped

volumes:
  postgres_data:
  redis_data:
  staticfiles: