# Generated by Django 5.2 on 2025-05-05 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_alter_team_logo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dashboard',
            name='score',
        ),
        migrations.AlterField(
            model_name='fanprofile',
            name='interacted_org_posts',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='fanprofile',
            name='liked_org_posts',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='fanprofile',
            name='rt_org_posts',
            field=models.IntegerField(default=0),
        ),
    ]
